**四种战斗机性能指标数据**

|         | 最大速度(马赫) | 飞行范围(km) | 最大负载(磅) | 费用(美元) | 可靠性 | 灵敏度 |
| :-----: | :------------: | :----------: | :----------: | :--------: | :----: | :----: |
|  $A_1$  |      2.0       |     1500     |    20000     |  5500000   |  一般  |  很高  |
|  $A_2$  |      2.5       |     2700     |    18000     |  6500000   |   低   |  一般  |
|  $A_3$  |      1.8       |     2000     |    21000     |  4500000   |   高   |   高   |
| $A_{4}$ |      2.2       |     1800     |    20000     |  5000000   |  一般  |  一般  |

假设将 6 项指标依次记为$x_1,x_2,…,x_6$，首先将$x_5$和$x_6$两项定性指标进行量化处理，量化后的数据如下表所示。

**可靠性与灵敏度指标量化值**

|         | 最大速度(马赫) | 飞行范围(km) | 最大负载(磅) | 费用(美元) | 可靠性 | 灵敏度 |
| :-----: | :------------: | :----------: | :----------: | :--------: | :----: | :----: |
|  $A_1$  |      2.0       |     1500     |    20000     |  5500000   |  0.5   |   1    |
|  $A_2$  |      2.5       |     2700     |    18000     |  6500000   |  0.3   |  0.5   |
|  $A_3$  |      1.8       |     2000     |    21000     |  4500000   |  0.7   |  0.7   |
| $A_{4}$ |      2.2       |     1800     |    20000     |  5000000   |  0.5   |  0.5   |

In [8]:
"""
一致化与无量纲化处理
"""
import numpy as np
from scipy.linalg import norm


# 0,1,2,4,5极大型指标， 3极小型指标
a = np.array([[2.0, 1500, 20000, 5500000, 0.5, 1],
              [2.5, 2700, 18000, 6500000, 0.3, 0.5],
              [1.8, 2000, 21000, 4500000, 0.7, 0.7],
              [2.2, 1800, 20000, 5000000, 0.5, 0.5]])

# 比例变换法
b = a / a.max(axis=0)
b[:, 3] = a[:, 3].min() / a[:, 3]
print(b, '\n')

# 向量归一法
b = a / norm(a, ord=2, axis=0)
b[:, 3] = 1 - b[:, 3]
print(b, '\n')

# 极差变换法（不保持比例）
b = (a - a.min(axis=0)) / a.ptp(axis=0)
b[:, 3] = (a[:, 3].max() - a[:, 3]) / a[:, 3].ptp()
print(b, '\n')

[[0.8        0.55555556 0.95238095 0.81818182 0.71428571 1.        ]
 [1.         1.         0.85714286 0.69230769 0.42857143 0.5       ]
 [0.72       0.74074074 1.         1.         1.         0.7       ]
 [0.88       0.66666667 0.95238095 0.9        0.71428571 0.5       ]] 

[[0.46714184 0.36618056 0.50556014 0.49314675 0.48112522 0.70888121]
 [0.58392729 0.659125   0.45500413 0.40099162 0.28867513 0.3544406 ]
 [0.42042765 0.48824074 0.53083815 0.58530189 0.67357531 0.49621684]
 [0.51385602 0.43941667 0.50556014 0.53922432 0.48112522 0.3544406 ]] 

[[0.28571429 0.         0.66666667 0.5        0.5        1.        ]
 [1.         1.         0.         0.         0.         0.        ]
 [0.         0.41666667 1.         1.         1.         0.4       ]
 [0.57142857 0.25       0.66666667 0.75       0.5        0.        ]] 



In [9]:
"""
一致化与无量纲化处理：利用scipy.preprocessing
"""

import numpy as np
from sklearn.preprocessing import MinMaxScaler, MaxAbsScaler, normalize

a = np.array([[2.0, 1500, 20000, 5500000, 0.5, 1],
              [2.5, 2700, 18000, 6500000, 0.3, 0.5],
              [1.8, 2000, 21000, 4500000, 0.7, 0.7],
              [2.2, 1800, 20000, 5000000, 0.5, 0.5]])

# 比例变换法
scaler_MaxAbs = MaxAbsScaler().fit(a)
print(scaler_MaxAbs.transform(a), '\n')

# 向量归一法
print(normalize(a, norm='l2', axis=0), '\n')

# 极差变换法（不保持比例）
scaler_MinMax = MinMaxScaler().fit(a)
print(scaler_MinMax.transform(a), '\n')

[[0.8        0.55555556 0.95238095 0.84615385 0.71428571 1.        ]
 [1.         1.         0.85714286 1.         0.42857143 0.5       ]
 [0.72       0.74074074 1.         0.69230769 1.         0.7       ]
 [0.88       0.66666667 0.95238095 0.76923077 0.71428571 0.5       ]] 

[[0.46714184 0.36618056 0.50556014 0.50685325 0.48112522 0.70888121]
 [0.58392729 0.659125   0.45500413 0.59900838 0.28867513 0.3544406 ]
 [0.42042765 0.48824074 0.53083815 0.41469811 0.67357531 0.49621684]
 [0.51385602 0.43941667 0.50556014 0.46077568 0.48112522 0.3544406 ]] 

[[0.28571429 0.         0.66666667 0.5        0.5        1.        ]
 [1.         1.         0.         1.         0.         0.        ]
 [0.         0.41666667 1.         0.         1.         0.4       ]
 [0.57142857 0.25       0.66666667 0.25       0.5        0.        ]] 



In [10]:
"""
熵权法求权重
"""
import numpy as np
import pandas as pd


b = np.array([
    [0.8       , 0.55555556, 0.95238095, 0.81818182, 0.71428571, 1.        ],
    [1.        , 1.        , 0.85714286, 0.69230769, 0.42857143, 0.5       ],
    [0.72      , 0.74074074, 1.        , 1.        , 1.        , 0.7       ],
    [0.88      , 0.66666667, 0.95238095, 0.9       , 0.71428571, 0.5       ]])
n, m = b.shape


p = b / b.sum(axis=0)
e = -1/np.log(n) * (p*np.log(p)).sum(axis=0) # 熵值
g = 1 - e
w = g / g.sum()
print(w)
w

# f = p @ w # 评价值
# print(f)
# df = pd.DataFrame(f, columns=['score'])
# df.index += 1
# df['rank'] = df['score'].rank(ascending=False)
# print(df)

[0.05825717 0.18704101 0.01220201 0.07000746 0.32552998 0.34696237]


array([0.05825717, 0.18704101, 0.01220201, 0.07000746, 0.32552998,
       0.34696237])

In [11]:
"""
TOPSIS 权重w_i = 1/m
"""
import numpy as np
import pandas as pd
from scipy.linalg import norm


b = np.array([
    [0.8       , 0.55555556, 0.95238095, 0.81818182, 0.71428571, 1.        ],
    [1.        , 1.        , 0.85714286, 0.69230769, 0.42857143, 0.5       ],
    [0.72      , 0.74074074, 1.        , 1.        , 1.        , 0.7       ],
    [0.88      , 0.66666667, 0.95238095, 0.9       , 0.71428571, 0.5       ]])


c_pos = b.max(axis=0) # 正理想解
c_neg = b.min(axis=0) # 负理想解
s_pos = norm(b-c_pos, axis=1)
s_neg = norm(b-c_neg, axis=1)
f = s_neg / (s_pos + s_neg)


# print(f)
df = pd.DataFrame(f, columns=['score'])
df.index += 1
df['rank'] = df['score'].rank(ascending=False)
print(df)

      score  rank
1  0.502948   2.0
2  0.387119   3.0
3  0.596731   1.0
4  0.376925   4.0


In [12]:
"""
TOPSIS 含权重
"""
import numpy as np
import pandas as pd
from scipy.linalg import norm


b = np.array([
    [0.8       , 0.55555556, 0.95238095, 0.81818182, 0.71428571, 1.        ],
    [1.        , 1.        , 0.85714286, 0.69230769, 0.42857143, 0.5       ],
    [0.72      , 0.74074074, 1.        , 1.        , 1.        , 0.7       ],
    [0.88      , 0.66666667, 0.95238095, 0.9       , 0.71428571, 0.5       ]])
n, m = b.shape

w = np.array([0.05825717, 0.18704101, 0.01220201, 0.07000746, 0.32552998, 0.34696237]) # 熵权
# w = np.full(m, 1/m) # 权重相等



c_pos = b.max(axis=0) # 正理想解
c_neg = b.min(axis=0) # 负理想解
s_pos = ((b-c_pos)**2 @ w)**.5
s_neg = ((b-c_neg)**2 @ w)**.5
f = s_neg / (s_pos + s_neg)


# print(f)
df = pd.DataFrame(f, columns=['score'])
df.index += 1
df['rank'] = df['score'].rank(ascending=False)
print(df)

      score  rank
1  0.564856   2.0
2  0.313043   4.0
3  0.624225   1.0
4  0.331980   3.0


In [13]:
"""
秩和比法 含权重
"""
import numpy as np
import pandas as pd
from scipy.stats import rankdata


b = np.array([
    [0.8       , 0.55555556, 0.95238095, 0.81818182, 0.71428571, 1.        ],
    [1.        , 1.        , 0.85714286, 0.69230769, 0.42857143, 0.5       ],
    [0.72      , 0.74074074, 1.        , 1.        , 1.        , 0.7       ],
    [0.88      , 0.66666667, 0.95238095, 0.9       , 0.71428571, 0.5       ]])
n, m = b.shape

# w = np.array([0.05825717, 0.18704101, 0.01220201, 0.07000746, 0.32552998, 0.34696237]) # 熵权
w = np.full(m, 1/m) # 权重相等



R = rankdata(b, axis=0) # 编秩
RSR = 1/n * (R @ w)


# print(RSR)
df = pd.DataFrame(RSR, columns=['score'])
df.index += 1
df['rank'] = df['score'].rank(ascending=False)
print(df)

      score  rank
1  0.583333   3.0
2  0.520833   4.0
3  0.791667   1.0
4  0.604167   2.0


In [14]:
"""
灰色关联度分析 含权重
"""
import numpy as np
import pandas as pd


b = np.array([
    [0.8       , 0.55555556, 0.95238095, 0.81818182, 0.71428571, 1.        ],
    [1.        , 1.        , 0.85714286, 0.69230769, 0.42857143, 0.5       ],
    [0.72      , 0.74074074, 1.        , 1.        , 1.        , 0.7       ],
    [0.88      , 0.66666667, 0.95238095, 0.9       , 0.71428571, 0.5       ]])
n, m = b.shape

# w = np.array([0.05825717, 0.18704101, 0.01220201, 0.07000746, 0.32552998, 0.34696237]) # 熵权
w = np.full(m, 1/m) # 权重相等


b_best = b.max(axis=0) # 参考序列
d = b - b_best 
m_min, m_max = np.min(np.abs(d)), np.max(np.abs(d)) # 最小差与最大差
rho = 0.5 # 灰色关联系数
xi = (m_min + rho*m_max) / (rho*m_max + np.abs(d))
f = xi @ w


# print(f)
df = pd.DataFrame(f, columns=['score'])
df.index += 1
df['rank'] = df['score'].rank(ascending=False)
print(df)

      score  rank
1  0.657966   2.0
2  0.640853   3.0
3  0.752855   1.0
4  0.604547   4.0
