## $\bigstar$ statsmodels

In [4]:
import numpy as np
import statsmodels.api as sm

np.set_printoptions(suppress=True)

X = np.array([[0, 0], 
              [0, 0.1], 
              [1, 1]])
y = np.array([0, 0, 1]) # 只能是1D

X = sm.add_constant(X) # 记得加入常数项

res = sm.Logit(y, X).fit(method="lbfgs")
print(res.params)
print(res.summary2())
# print(res.summary())

print(res.predict(X)) # <0.5为0，>0.5为1

[-11.89049529  12.49843864  10.78652134]
                          Results: Logit
Model:              Logit            Pseudo R-squared: 1.000      
Dependent Variable: y                AIC:              6.0001     
Date:               2022-08-26 22:53 BIC:              3.2959     
No. Observations:   3                Log-Likelihood:   -3.8272e-05
Df Model:           2                LL-Null:          -1.9095    
Df Residuals:       0                LLR p-value:      0.14815    
Converged:          1.0000           Scale:            1.0000     
No. Iterations:     15.0000                                       
-------------------------------------------------------------------
         Coef.     Std.Err.     z     P>|z|     [0.025      0.975] 
-------------------------------------------------------------------
const   -11.8905   381.9366  -0.0311  0.9752   -760.4724   736.6914
x1       12.4984  4106.7542   0.0030  0.9976  -8036.5919  8061.5887
x2       10.7865  4421.3385   0.0024  0.99

## sklearn.linear_model中的LogisticRegression
> 一般用来做多分类，不适合用于回归

- 检验指标只有$R^2$

- penalty惩罚项，类似lasso和ridge

penalty{‘l1’, ‘l2’, ‘elasticnet’, ‘none’}, default=’l2’

Specify the norm of the penalty:

'none': no penalty is added;

'l2': add a L2 penalty term and it is the default choice;

'l1': add a L1 penalty term;

'elasticnet': both L1 and L2 penalty terms are added.



In [2]:
import numpy as np
from sklearn.linear_model import LogisticRegression

np.set_printoptions(suppress=True)

X = np.array([[0, 0], 
              [0, 0.1], 
              [1, 1]])
y = np.array([0, 0, 1])

clf = LogisticRegression(random_state=1, solver='lbfgs', penalty='none', tol=1e-4).fit(X, y) # 最简单的形式

print(clf.intercept_, clf.coef_, sep='\n')
print('-'*30)

print(clf.score(X, y))

print(clf.predict(X)) # 直接输出分类的标签
print(clf.predict_proba(X)) # 输出对各个标签的概率


[-10.41511893]
[[10.92702622  9.49018677]]
------------------------------
1.0
[0 0 1]
[[0.99997003 0.00002997]
 [0.99992257 0.00007743]
 [0.0000453  0.9999547 ]]
