## 距离判别法（多分类判别） sklearn.neighbors.KNeighborsClassifier

> https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsClassifier.html#sklearn.neighbors.KNeighborsClassifier

优缺点：
- **马氏距离**，它不受量纲的影响,两点之间的马氏距离与原始数据的测量单位无关；由标准化数据和中心化数据(即原始数据与均值之差）计算出的二点之间的马氏距离相同.马氏距离还可以排除变量之间的相关性的干扰.它的缺点是夸大了变化微小的变量的作用.

- 欧氏距离，的优点简单有用，易于理解，缺点：它将样品的不同属性（即各指标或各变量）之间的差别等同看待,这一点有时不能满足实际要求.

---

- metric: 'minkowski'&p=2, 'euclidean', 'mahalanobis'马氏距离, 'seuclidean'数据标准化欧式距离
- kneighbors(X=None, n_neighbors=None, return_distance=True) ：返回k近邻点的距离和下标


KNN方法在类别决策时，只与极少量的相邻样本有关。由于KNN方法主要靠周围有限的邻近的样本，而不是靠判别类域的方法来确定所属类别的，因此**对于类域的交叉或重叠较多的待分样本集**来说，KNN方法较其他方法更为适合。


---

计算最近k个点的算法：kd-Tree
https://zhuanlan.zhihu.com/p/393775739

In [2]:
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
np.set_printoptions(precision=8, suppress=True)

X = np.array([[1.24,1.27], 
              [1.36,1.74], 
              [1.38,1.64], 
              [1.38,1.82], 
              [1.38,1.90], 
              [1.40,1.70],
              [1.48,1.82], 
              [1.54,1.82], 
              [1.56,2.08],
              [1.14,1.78], 
              [1.18,1.96], 
              [1.20,1.86],
              [1.26,2.00], 
              [1.28,2.00], 
              [1.30,1.96]])
y = np.hstack([np.ones(9), 2*np.ones(6)])
X_test = np.array([[1.24,1.80], 
                   [1.28,1.84], 
                   [1.40,2.04]])

cov_X = np.cov(X.T) # 协方差矩阵
knn = KNeighborsClassifier(n_neighbors=2, metric='mahalanobis', metric_params={'V': cov_X}).fit(X,y) #马氏距离分类

print(knn.predict(X_test))
print(knn.score(X, y)) # 准确率
print(knn.kneighbors(X_test, return_distance=True))
# print(1 - knn.score(X, y)) # 误判率
print('-'*30)

knn1 = KNeighborsClassifier(n_neighbors=2).fit(X, y) # 欧氏距离分类

print(knn1.predict(X_test))
print(knn1.score(X, y)) # 准确率
print('-'*30)

print(knn.kneighbors(X_test, return_distance=True)) # 最近k个点

[2. 2. 1.]
1.0
(array([[0.47518672, 0.79137595],
       [0.61718552, 0.66182395],
       [0.71739148, 0.84641816]]), array([[11,  9],
       [14, 11],
       [ 4, 14]], dtype=int64))
------------------------------
[2. 1. 2.]
1.0
------------------------------
(array([[0.47518672, 0.79137595],
       [0.61718552, 0.66182395],
       [0.71739148, 0.84641816]]), array([[11,  9],
       [14, 11],
       [ 4, 14]], dtype=int64))


## 参数选择

- **网格搜索**
- **交叉验证法**
- 排序求出最好的参数

> KNN中K值大小选择对模型的影响 - 黑马程序员的文章 - 知乎  https://zhuanlan.zhihu.com/p/526415029